config/routes.rb
OurStudio::Application.routes.draw do
  get "home/index"

  resources :songs

  root :to => 'home#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  mount_uploader :attachment, MusicUploader
  attr_accessible :attachment, :uploader_email, :uploader_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<div class="hero-unit text-align-center">
  <h1>Our Studio</h1>

  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris libero quam, luctus vel lobortis eget, sollicitudin
    ac leo. Phasellus fermentum semper euismod. In at elit orci, in vehicula risus. Etiam nisi odio, pretium et
    imperdiet at, accumsan at dui. Fusce vitae elit ut enim tempus tempor.
  </p>

  <h3>Its your studio. Get featured here</h3>

  <p>

  <div class="offset3">
    <%= form_for Song.new, :html => {:class => 'form-horizontal text-align-left'} do |f| %>
        <div class="control-group">
          <%= f.label :uploader_name, "Your Name", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :uploader_name, :placeholder => 'Your full name', :required => true %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :uploader_email, "Your Email", :class => 'control-label' %>
          <div class="controls">
            <%= f.email_field :uploader_email, :placeholder => 'name@email.com', :required => true %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :attachment, "Your Songs", :class => 'control-label' %>
          <div class="controls">
            <%= f.file_field :attachment, multiple: true, name: "song[attachment]", required: true %>
          </div>
        </div>
    <% end %>
  </div>
  </p>
</div>

<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%;"></div></div>
  </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "OurStudio" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%#= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'OurStudio', root_path, :class => 'brand' %>

      <div class="container nav-collapse">
        <!--<ul class="nav">-->
          <!--<li><%#= link_to "Link1", "/path1" %></li>-->
          <!--<li><%#= link_to "Link2", "/path2" %></li>-->
          <!--<li><%#= link_to "Link3", "/path3" %></li>-->
        <!--</ul>-->
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container top-container">
  <div class="row">
    <div class="span12">
      <%= yield %>
    </div>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; Our Studio 2013</p>
  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :create %><br />
    <%= f.text_field :create %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Create</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.create %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Create:</b>
  <%= @song.uploader_name %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>